# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import timer_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 244)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/my_foto.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.Time = QtWidgets.QLineEdit(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(10, 20, 331, 71))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(36)
        self.Time.setFont(font)
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setReadOnly(True)
        self.Time.setObjectName("Time")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(210, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(210, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(28)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName("pushButton")
        self.reset_btn.hide()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 220, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.Time.setText(_translate("MainWindow", "00:00:00:00"))
        self.stop_btn.setText(_translate("MainWindow", "STOP"))
        self.reset_btn.setText(_translate("MainWindow", "RESET"))
        self.label.setText(_translate("MainWindow", "Krupeichenko Victor"))
